---
title: "Clustering"
author: "Edo Danilyan"
date: '2022-03-27'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
library(tidyverse)
summary(mtcars)
View(mtcars)
dat <- data.table::data.table(mtcars, keep.rownames = TRUE) #Proses agar nama kolomnya muncul
datahi <- dat |> filter(str_detect(rn, "^M|^T")) #Proses memilih sebagian mobil berdasarkan awalan huruf

datahimat <- datahi |> column_to_rownames(var = "rn")  #Mengembalikan tipe data agar dapat dilakukan  perhitungan dist matrix
View(datahimat)
distance_matdat <- dist(datahimat, method = 'euclidean')
hierar_datahimat <- hclust(distance_matdat, method = "complete")
plot(hierar_datahimat, main = "Dendogram Cars")

```

# Hierarchial clustering

```{r, echo=FALSE}
library(factoextra)
head(mtcars)
?mtcars
View(mpg)
mpg |>
  filter(manufacturer %in% c("audi", "dogde", "ford"))
mpgtry <- mpg |>
  filter(manufacturer %in% c("audi", "dogde", "ford")) |>
  drop_na()
View(mpgtry)
distance_mat1 <- dist(mpgtry, method = 'euclidean')
distance_mat <- dist(mtcars, method = 'euclidean')
set.seed(240)
Hierar_cl <- hclust(distance_mat, method = "complete")
plot(Hierar_cl, main = "Dendogram Cars")
rect.hclust(Hierar_cl, k = 3, border = 2:4)

```

# Input manual: data mie instan di indo

```{r}


mie_instan <- data.frame(nama = c("Indomie rendang", "Indomie soto", "Indomie kari", "Sedap goreng", "Sedap soto", "sedap kari"),
                         kuah = c(0, 1, 1, 0, 1, 1),
                         garam = c(1.5, 1.4, 1.5, 1.8, 2, 2.1),
                         fiber = c(10, 12, 12, 15, 15, 15),
                         kalori = c(1015, 1016, 1017, 1700, 1750, 1690))
View(mie_instan)
head(mie_instan)
datamie <- mie_instan |> column_to_rownames(var = "nama")
dist_mie <- dist(datamie, method = 'euclidean')
clust_mie <- hclust(dist_mie, method = "average")
plot(clust_mie)

```

# Iris Data
```{r}
iris
iris_labels <- iris$Species
table(iris_labels)

# Data
iris_data <- iris[1:4]

# Scaling
iris_data_std <- scale(iris_data)

# Distance
iris_dist <- dist(iris_data_std)

# Hierarchical clustering
hc_out_iris <- hclust(iris_dist, method = "complete")
hc_out_iris

# Dendogram
plot(hc_out_iris)
rect.hclust(hc_out_iris, k = 3, border = 2:5)

# Clusters
iris_clusters <- cutree(hc_out_iris, k = 3)

# Visual
rownames(iris_data_std) <- paste(iris$Species, 1:dim(iris)[1], sep ="_")
fviz_cluster(list(data = iris_data_std, cluster = iris_clusters), ellipse.type = "norm", ggtheme = theme_minimal(), palette = "Set2")

```

